/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as EthicsRouteImport } from './routes/ethics'
import { Route as CorrectionsRouteImport } from './routes/corrections'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthorsRouteImport } from './routes/authors'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CategoryRouteImport } from './routes/$category'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatesStateRouteImport } from './routes/states.$state'
import { Route as AuthorsSlugRouteImport } from './routes/authors.$slug'
import { Route as CategorySlugRouteImport } from './routes/$category.$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const EthicsRoute = EthicsRouteImport.update({
  id: '/ethics',
  path: '/ethics',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrectionsRoute = CorrectionsRouteImport.update({
  id: '/corrections',
  path: '/corrections',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsRoute = AuthorsRouteImport.update({
  id: '/authors',
  path: '/authors',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryRoute = CategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatesStateRoute = StatesStateRouteImport.update({
  id: '/states/$state',
  path: '/states/$state',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsSlugRoute = AuthorsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthorsRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CategoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$category': typeof CategoryRouteWithChildren
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/authors': typeof AuthorsRouteWithChildren
  '/contact': typeof ContactRoute
  '/corrections': typeof CorrectionsRoute
  '/ethics': typeof EthicsRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/$category/$slug': typeof CategorySlugRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/states/$state': typeof StatesStateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$category': typeof CategoryRouteWithChildren
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/authors': typeof AuthorsRouteWithChildren
  '/contact': typeof ContactRoute
  '/corrections': typeof CorrectionsRoute
  '/ethics': typeof EthicsRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/$category/$slug': typeof CategorySlugRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/states/$state': typeof StatesStateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$category': typeof CategoryRouteWithChildren
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/authors': typeof AuthorsRouteWithChildren
  '/contact': typeof ContactRoute
  '/corrections': typeof CorrectionsRoute
  '/ethics': typeof EthicsRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/$category/$slug': typeof CategorySlugRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/states/$state': typeof StatesStateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$category'
    | '/about'
    | '/archive'
    | '/authors'
    | '/contact'
    | '/corrections'
    | '/ethics'
    | '/privacy'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/$category/$slug'
    | '/authors/$slug'
    | '/states/$state'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$category'
    | '/about'
    | '/archive'
    | '/authors'
    | '/contact'
    | '/corrections'
    | '/ethics'
    | '/privacy'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/$category/$slug'
    | '/authors/$slug'
    | '/states/$state'
  id:
    | '__root__'
    | '/'
    | '/$category'
    | '/about'
    | '/archive'
    | '/authors'
    | '/contact'
    | '/corrections'
    | '/ethics'
    | '/privacy'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/$category/$slug'
    | '/authors/$slug'
    | '/states/$state'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoryRoute: typeof CategoryRouteWithChildren
  AboutRoute: typeof AboutRoute
  ArchiveRoute: typeof ArchiveRoute
  AuthorsRoute: typeof AuthorsRouteWithChildren
  ContactRoute: typeof ContactRoute
  CorrectionsRoute: typeof CorrectionsRoute
  EthicsRoute: typeof EthicsRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  StatesStateRoute: typeof StatesStateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ethics': {
      id: '/ethics'
      path: '/ethics'
      fullPath: '/ethics'
      preLoaderRoute: typeof EthicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corrections': {
      id: '/corrections'
      path: '/corrections'
      fullPath: '/corrections'
      preLoaderRoute: typeof CorrectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors': {
      id: '/authors'
      path: '/authors'
      fullPath: '/authors'
      preLoaderRoute: typeof AuthorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$category': {
      id: '/$category'
      path: '/$category'
      fullPath: '/$category'
      preLoaderRoute: typeof CategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/states/$state': {
      id: '/states/$state'
      path: '/states/$state'
      fullPath: '/states/$state'
      preLoaderRoute: typeof StatesStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/$slug': {
      id: '/authors/$slug'
      path: '/$slug'
      fullPath: '/authors/$slug'
      preLoaderRoute: typeof AuthorsSlugRouteImport
      parentRoute: typeof AuthorsRoute
    }
    '/$category/$slug': {
      id: '/$category/$slug'
      path: '/$slug'
      fullPath: '/$category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof CategoryRoute
    }
  }
}

interface CategoryRouteChildren {
  CategorySlugRoute: typeof CategorySlugRoute
}

const CategoryRouteChildren: CategoryRouteChildren = {
  CategorySlugRoute: CategorySlugRoute,
}

const CategoryRouteWithChildren = CategoryRoute._addFileChildren(
  CategoryRouteChildren,
)

interface AuthorsRouteChildren {
  AuthorsSlugRoute: typeof AuthorsSlugRoute
}

const AuthorsRouteChildren: AuthorsRouteChildren = {
  AuthorsSlugRoute: AuthorsSlugRoute,
}

const AuthorsRouteWithChildren =
  AuthorsRoute._addFileChildren(AuthorsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoryRoute: CategoryRouteWithChildren,
  AboutRoute: AboutRoute,
  ArchiveRoute: ArchiveRoute,
  AuthorsRoute: AuthorsRouteWithChildren,
  ContactRoute: ContactRoute,
  CorrectionsRoute: CorrectionsRoute,
  EthicsRoute: EthicsRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  StatesStateRoute: StatesStateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
